services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    environment:
      - TZ=${TZ}
    volumes:
      - ${SHARE_ROOT}:/share
    command: >
      -u "${SMB_USER};${SMB_PASS}"
      -s "share;/share;yes;no;no;${SMB_USER}"
      -p
